Repository AY2324S2-CS2103T-T11-4/tp, pull requests merged in 2024-04, with the labels that each got.

#83 Bug fix: remove dangling tag label
  src/main/java/seedu/address/logic/Messages.java
Labels: bug

#82 Implement Deletetag Command
  src/main/java/seedu/address/logic/commands/DeletetagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletetagCommandParser.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/DeletetagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletetagCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: enhancement, priority.High

#97 Branch/warning popup
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/WarningWindow.java
  src/main/resources/images/warning_icon.png
  src/main/resources/view/WarningWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: enhancement

#109 Branch update edittaglist msg
  src/main/java/seedu/address/logic/commands/EditTutTagListCommand.java
  src/main/java/seedu/address/logic/parser/EditTutTagListCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniqueTutorialTagList.java
  src/main/java/seedu/address/model/tag/TutorialTag.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTutTagListCommandTest.java
  src/test/java/seedu/address/logic/parser/EditTutTagListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: bug, enhancement, priority.High

#111 Update tuttag del
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeletetagCommand.java
  src/main/java/seedu/address/logic/commands/EditTutTagListCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTutTagListCommandTest.java
Labels: bug

#184 [TesterA #158, #156, #130] Fix TesterA UG Bugs
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: bug

#185 [Tester A #147] Update duplicate id behaviour in ug
  docs/UserGuide.md
Labels: bug

#188 [TesterE #144, #140] Fix TesterE UG Bugs
  docs/UserGuide.md
Labels: documentation

#190 Fix Available command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AvailableCommand.java
  src/main/java/seedu/address/logic/parser/AvailableCommandParser.java
  src/test/java/seedu/address/logic/parser/AvailableCommandParserTest.java
Labels: bug

#194 Add tagging class diagram in DG
  docs/DeveloperGuide.md
  docs/diagrams/TaggingClassDiagram.puml
  docs/images/TaggingClassDiagram.png
Labels: documentation

#198 Update DG with tuttag activity diagram and Planned Enhancements
  docs/DeveloperGuide.md
  docs/diagrams/TuttagActivityDiagram.puml
  docs/images/TuttagActivityDiagram.png
Labels: documentation

#201 Fix the incorrect error message
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/StatefulParserUtil.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
Labels: bug

#214 Update index.md
  docs/index.md
Labels: documentation
